spring.application.name=wallet-service

springdoc.swagger-ui.enabled=false

spring.datasource.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.h2.console.enabled=false

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

spring.cache.type=${CACHE_TYPE:redis}
spring.cache.redis.time-to-live=5m
spring.cache.redis.key-prefix=${spring.application.name}:

management.health.redis.enabled=false

logging.structured.format.console=ecs
logging.level.root=INFO
logging.level.com.example.wallet=INFO
