spring.application.name=wallet-service

spring.datasource.url=jdbc:h2:file:./data/wallet-service;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=200ms
spring.data.redis.client-type=lettuce
spring.data.redis.lettuce.shutdown-timeout=100ms

spring.cache.type=redis
spring.cache.redis.time-to-live=24h

management.health.redis.enabled=false

