springdoc.swagger-ui.enabled=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

logging.structured.format.console=
logging.level.com.example.wallet=DEBUG
logging.level.org.hibernate.SQL=DEBUG
